spring:
  application:
    name: auth-service
  security:
    user:
      name: admin
      password: admin123
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: root
    password: root
    hikari:
      pool-name: eazyBank-pool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG








